language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphicsmagick libreoffice-common
script:
  - rake test
  - rubocop
notifications:
  email: false
