language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice
  - wget http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-1.3.18.tar.gz
  - tar -xvf GraphicsMagick-1.3.18.tar.gz
  - cd GraphicsMagick-1.3.18
  - ./configure
  - make
  - sudo make install
  # Launch Poleica for the first time
  - ruby -Ilib -rpoleica -e "Poleica.new('test/support/files/example.doc').to_pdf"
  - rm test/support/files/example-1eb0afc1a8a2179e723c58a49d5a84c6.pdf
script:
  - rake
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
notifications:
  email: false
