language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.1
  - 2.0
  - 2.2
  - rbx-2
  - jruby-19mode
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice
  - wget http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-1.3.18.tar.gz
  - tar -xvf GraphicsMagick-1.3.18.tar.gz
  - cd GraphicsMagick-1.3.18
  - ./configure
  - make
  - sudo make install
  - /usr/lib/libreoffice/program/soffice.bin --nologo --headless --invisible --norestore --nolockcheck --convert-to pdf test/support/files/example.doc || true
script:
  - bundle exec rake
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-19mode
notifications:
  email: false
