language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libreoffice
  - wget http://78.108.103.11/MIRROR/ftp/GraphicsMagick/1.3/GraphicsMagick-1.3.18.tar.gz
  - tar -xvf GraphicsMagick-1.3.18.tar.gz
  - cd GraphicsMagick-1.3.18
  - ./configure
  - make
  - sudo make install
  - sudo ln -s /usr/local/bin/gm /usr/bin/gm
  # Try with a ping
  - /usr/lib/libreoffice/program/soffice.bin
script:
  - rake
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
notifications:
  email: false
