language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - rbx-19mode
  - jruby-19mode
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphicsmagick
script:
  - rake test
  - rubocop